/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as FavouriteRouteImport } from './favourite'
import { Route as IndexRouteImport } from './index'

const FavouriteRoute = FavouriteRouteImport.update({
  id: '/favourite',
  path: '/favourite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favourite': typeof FavouriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favourite': typeof FavouriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favourite': typeof FavouriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favourite'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favourite'
  id: '__root__' | '/' | '/favourite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavouriteRoute: typeof FavouriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favourite': {
      id: '/favourite'
      path: '/favourite'
      fullPath: '/favourite'
      preLoaderRoute: typeof FavouriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavouriteRoute: FavouriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
